
package stateless_soap_websevice_stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "webservice_testerService", targetNamespace = "http://stateless_SOAP_webservice_using_Eclipse/", wsdlLocation = "http://localhost:7004/FirstEJB/webservice_tester?wsdl")
public class WebserviceTesterService
    extends Service
{

    private final static URL WEBSERVICETESTERSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICETESTERSERVICE_EXCEPTION;
    private final static QName WEBSERVICETESTERSERVICE_QNAME = new QName("http://stateless_SOAP_webservice/", "webservice_testerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7004/FirstEJB/webservice_tester?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICETESTERSERVICE_WSDL_LOCATION = url;
        WEBSERVICETESTERSERVICE_EXCEPTION = e;
    }

    public WebserviceTesterService() {
        super(__getWsdlLocation(), WEBSERVICETESTERSERVICE_QNAME);
    }

    public WebserviceTesterService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICETESTERSERVICE_QNAME, features);
    }

    public WebserviceTesterService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICETESTERSERVICE_QNAME);
    }

    public WebserviceTesterService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICETESTERSERVICE_QNAME, features);
    }

    public WebserviceTesterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebserviceTesterService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebserviceTesterRemote
     */
    @WebEndpoint(name = "webservice_testerPort")
    public WebserviceTesterRemote getWebserviceTesterPort() {
        return super.getPort(new QName("http://stateless_SOAP_webservice/", "webservice_testerPort"), WebserviceTesterRemote.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebserviceTesterRemote
     */
    @WebEndpoint(name = "webservice_testerPort")
    public WebserviceTesterRemote getWebserviceTesterPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://stateless_SOAP_webservice_using_Eclipse/", "webservice_testerPort"), WebserviceTesterRemote.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICETESTERSERVICE_EXCEPTION!= null) {
            throw WEBSERVICETESTERSERVICE_EXCEPTION;
        }
        return WEBSERVICETESTERSERVICE_WSDL_LOCATION;
    }

}
